apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "onride"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "onride"
    spec:
      containers:
        - name: "onride"
          image: "clase.azurecr.io/onride"
          ports:
          - containerPort: 1433