on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n Clase -g Clase9fed-rg --location "France Central" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n Clase --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n Clase --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n Clase --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: clase.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/01-mssql-deploy/pvc.yaml" -f  "01-mssql-deploy/mssql.yaml" -t clase.azurecr.io/onride:${{ github.sha }}
        docker push clase.azurecr.io/onride:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_onride_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep onride13bf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace onride13bf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: onride13bf
        container-registry-url: clase.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: onridedockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: onride13bf
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          clase.azurecr.io/onride:${{ github.sha }}
        imagepullsecrets: |
          onridedockerauth